// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBlog = "blog"

// Blog mapped from table <blog>
type Blog struct {
	BlogID     int32     `gorm:"column:blog_id;primaryKey;autoIncrement:true;comment:主键" json:"blog_id"`
	Title      string    `gorm:"column:title;not null;comment:标题" json:"title"`
	Content    string    `gorm:"column:content;comment:内容" json:"content"`
	PostTime   time.Time `gorm:"column:post_time;default:CURRENT_TIMESTAMP;comment:发表时间" json:"post_time"`
	ReadCount  int32     `gorm:"column:read_count;comment:阅读量" json:"read_count"`
	UserID     int32     `gorm:"column:user_id;comment:用户表外键" json:"user_id"`
	IsDelete   int32     `gorm:"column:is_delete;comment:标识是否删除记录" json:"is_delete"`
	CategoryID int32     `gorm:"column:category_id;comment:分类外键" json:"category_id"`
}

// TableName Blog's table name
func (*Blog) TableName() string {
	return TableNameBlog
}
