// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCategory = "category"

// Category mapped from table <category>
type Category struct {
	CategoryID   int32  `gorm:"column:category_id;primaryKey;autoIncrement:true;comment:分类ID，自增ID" json:"category_id"`
	CategoryName string `gorm:"column:category_name;not null;comment:分类名称" json:"category_name"`
}

// TableName Category's table name
func (*Category) TableName() string {
	return TableNameCategory
}
