// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	UserID     int32     `gorm:"column:user_id;primaryKey;autoIncrement:true;comment:主键" json:"user_id"`
	Username   string    `gorm:"column:username;not null;comment:用户名" json:"username"`
	Password   string    `gorm:"column:password;not null;comment:密码" json:"password"`
	Tel        string    `gorm:"column:tel;comment:手机号" json:"tel"`
	CreateTime time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"`
	IsDelete   int32     `gorm:"column:is_delete;comment:标识是否删除记录" json:"is_delete"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
